const notifications = [
  {
    id: 1,
    title: "Results Published",
    message: "Semester 4 results have been published. Click to view your marks.",
    type: "success",
    category: "Results",
    date: "Today",
    time: "10:30 AM",
    important: true,
    read: false,
  },
  {
    id: 2,
    title: "Attendance Updated",
    message: "Your attendance has been updated for today's classes.",
    type: "success",
    category: "Attendance",
    date: "Today",
    time: "09:15 AM",
    important: false,
    read: false,
  },
  {
    id: 3,
    title: "Attendance Alert",
    message: "Your attendance is below 75%. Please attend classes regularly.",
    type: "urgent",
    category: "Attendance",
    date: "Today",
    time: "08:00 AM",
    important: true,
    read: false,
  },
  {
    id: 4,
    title: "Assignment Reminder",
    message: "AI Lab Assignment-3 must be submitted by tomorrow.",
    type: "warning",
    category: "Assignment",
    date: "Yesterday",
    time: "04:30 PM",
    important: true,
    read: true,
  },
  {
    id: 5,
    title: "Exam Time Table Released",
    message: "The Mid-1 examination timetable has been uploaded.",
    type: "general",
    category: "Exams",
    date: "Yesterday",
    time: "11:20 AM",
    important: false,
    read: true,
  },
  {
    id: 6,
    title: "Fee Payment Reminder",
    message: "Pay your semester fee before 15 August to avoid late charges.",
    type: "urgent",
    category: "Fees",
    date: "2 Days Ago",
    time: "03:45 PM",
    important: true,
    read: false,
  },
  {
    id: 7,
    title: "Placement Drive",
    message: "Infosys placement drive registrations are now open.",
    type: "general",
    category: "Placements",
    date: "2 Days Ago",
    time: "10:00 AM",
    important: false,
    read: false,
  },
  {
    id: 8,
    title: "Workshop Registration",
    message: "Register for the AI & Machine Learning Workshop.",
    type: "general",
    category: "Workshop",
    date: "3 Days Ago",
    time: "01:00 PM",
    important: false,
    read: true,
  },
  {
    id: 9,
    title: "Holiday Notice",
    message: "College will remain closed tomorrow on account of Independence Day.",
    type: "general",
    category: "Holiday",
    date: "3 Days Ago",
    time: "09:30 AM",
    important: false,
    read: true,
  },
  {
    id: 10,
    title: "Library Book Due",
    message: "Please return your library book within the next two days.",
    type: "warning",
    category: "Library",
    date: "This Week",
    time: "02:15 PM",
    important: false,
    read: false,
  },
];

export default notifications;